---
services:
  cookbook-couchdb:
    image: couchdb:latest
    container_name: cookbook-couchdb
    hostname: cookbook-couchdb
    environment:
      - COUCHDB_USER=${COUCHDB_USER:-admin}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD:-admin}
    ports:
      - 5984:5984
    volumes:
      - ./mnt/etc/local.d/:/opt/couchdb/etc/local.d/
      - ./mnt/data:/opt/couchdb/data
    restart: unless-stopped
  cookbook-app:
    depends_on:
      - cookbook-couchdb
    image: ${COOKBOOK_IMAGE:-ghcr.io/mryachanin/cookbook-app:latest}
    ports:
      - 0.0.0.0:8080:8080
    volumes:
      - ./config_json:/root/config.json
    restart: unless-stopped
