---
version: "3.8"
services:
  cookbook-couchdb:
    image: couchdb:latest
    container_name: cookbook-couchdb
    hostname: cookbook-couchdb
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    ports:
      - 5984:5984
    volumes:
      - ./mnt/etc/local.d/:/opt/couchdb/etc/local.d/
      - ./mnt/data:/opt/couchdb/data
    restart: unless-stopped
  cookbook-app:
    depends_on:
      - cookbook-couchdb
    image: ghcr.io/mryachanin/cookbook-app:latest
    ports:
      - 0.0.0.0:8080:8080
    volumes:
      - ./config_json:/usr/src/app/config.json
    restart: unless-stopped
